[package]
name = "shader_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.13", features = [ "derive" ] }
memoffset = "0.8.0"
pixels = "0.11.0"
wgpu = "0.14.2"


[build-dependencies]
wgsl_to_wgpu = "0.3.1"
