[package]
name = "shader_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
nanoserde = "0.1.32"
spirv-builder = "0.5.0"
